name: Deploy to testServer
on:
  # master 브랜치로 PR될 때 마다 이 workflow를 수행
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: remote ssh
        run: |
          echo "############# CREATE .ENV #############"
          cd ../../main
          [ -f .env.local ] && rm .env.local
          touch .env.local
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> .env.local
          cat .env.local
          sh script.sh
